export const supriseMePrompts=[
    "A futuristic cityscape at sunset, with flying cars and neon lights.",
    "A serene forest with a hidden waterfall and glowing mushrooms.",
    "A steampunk airship floating above a Victorian-era city.",
    "A majestic dragon perched on a mountain peak during a thunderstorm.",
    "A cozy, magical library with floating books and enchanted candles.",
    "A cyberpunk street market bustling with diverse characters and holographic signs.",
    "A tranquil beach at dawn with bioluminescent waves.",
    "A medieval castle surrounded by a mystical fog.",
    "A space station orbiting a colorful nebula.",
    "A whimsical treehouse village in a giant, ancient tree.",
    "A futuristic robot serving coffee in a sleek, modern café.",
    "A fantasy landscape with floating islands and waterfalls cascading into the sky.",
    "A retro diner in the 1950s with classic cars parked outside.",
    "A magical forest with unicorns grazing under a rainbow.",
    "A bustling alien marketplace on a distant planet.",
    "A serene Japanese garden with cherry blossoms in full bloom.",
    "A haunted mansion on a hill during a full moon.",
    "A futuristic underwater city with glowing sea creatures.",
    "A cozy cabin in the woods during a snowy winter night.",
    "A vibrant carnival with colorful rides and fireworks.",
    "A mystical cave with glowing crystals and an underground river.",
    "A futuristic sports arena with holographic displays.",
    "A peaceful meadow with wildflowers and butterflies.",
    "A bustling medieval marketplace with vendors and street performers.",
    "A serene mountain lake with a reflection of the starry night sky.",
    "A futuristic laboratory with advanced technology and robots.",
    "A magical forest clearing with fairies and fireflies.",
    "A bustling cityscape with towering skyscrapers and flying vehicles.",
    "A tranquil Zen garden with a koi pond and stone lanterns.",
    "A fantasy castle floating in the clouds.",
    "A futuristic train speeding through a neon-lit tunnel.",
    "A cozy coffee shop with a view of a rainy city street.",
    "A mystical forest with ancient ruins and overgrown vines.",
    "A vibrant coral reef teeming with colorful marine life.",
    "A futuristic spaceport with starships and aliens.",
    "A serene countryside with rolling hills and a quaint farmhouse.",
    "A bustling cyberpunk nightclub with neon lights and futuristic music.",
    "A peaceful beach with a hammock and a view of the sunset.",
    "A magical library with enchanted books and floating candles.",
    "A futuristic city park with robotic gardeners and holographic art.",
    "A tranquil forest with a hidden waterfall and glowing mushrooms.",
    "A bustling medieval tavern with lively patrons and a roaring fireplace.",
    "A serene mountain landscape with a crystal-clear lake.",
    "A futuristic cityscape with flying cars and neon lights.",
    "A cozy cabin in the woods during a snowy winter night.",
    "A vibrant carnival with colorful rides and fireworks.",
    "A mystical cave with glowing crystals and an underground river.",
    "A futuristic sports arena with holographic displays.",
    "A peaceful meadow with wildflowers and butterflies.",
    "A bustling medieval marketplace with vendors and street performers."
  ];